### ISSUE TITLE
Example for Prediction of Atomization energies from molecular Geometry

### ISSUE THREAD

**Issue by thegodone** [jonas-koehler/s2cnn#11]
Can you add an example of implementation of the 5.4 part of your article please?

**Comment by antigol** [comment]
I uploaded the MNIST example but I need the help of @jonas-koehler for the molecule experiment.

**Comment by thegodone** [comment]
thanks for help, I will wait jonas update.

**Comment by jonas-koehler** [comment]
Sorry for the late response. I just added the example.
