### ISSUE TITLE
summary.csv is empty after running test.py

### ISSUE THREAD

**Issue by LiZimo** [jonas-koehler/s2cnn#12]
First, thanks for the great work.  Super interesting.

Wondering what node version to use?  I had to edit the evaluator script as some things don't work with node v0.10.25.

**Main issue:** 
After running test.py with no errors, summary.csv is empty.  Furthermore, running **./evaluate.js ../myrun/** also doesn't work.  The final printout is "Loaded Evaluator using file all.csv.gz
../my_run/val_perturbed/...".  Any advice on what I should do?

NOTE:

I ran test.py with the -augmentations  set to 1.  Don't know if this would effect anything?  I'll run it again with higher number of augmentations if necessary.  Thanks!

**Comment by antigol** [comment]
You can keep `--augmentation 1` it changes nothing for the js script.
The script `test.py` creates a folder `val_perturbed` into your folder `my_run` and fill it with plenty of files: `000009, 000022, 000023, 000029, 000031, 000037, 000047, ....` (one per 3d model). 
Each of those files contains the ids of other 3d models, one per line.

Then it runs the official evaluator of the task ([from this page](https://shapenet.cs.stanford.edu/shrec17/)).

Can you check if the content of `val_perturbed` looks correct ?

**Comment by LiZimo** [comment]
Hi.  Yes, `val_perturbed ` looks correct.  There are 5133 files numbered in the style mentioned. 

 I'm starting to think its just an issue with the evaluation script not being compatible with my version of node.  Can I ask what version you are using?

**Comment by LiZimo** [comment]
Ah, yea it was just my nodejs version.  I just updated it and it was fine.  I thought I was using the latest one but I actually had 2 versions installed.  Thanks, and sorry for the trouble!
