### ISSUE TITLE
Can you release a version of CPU-only?

### ISSUE THREAD

**Issue by zhixuanli** [jonas-koehler/s2cnn#13]
Hi, I'm trying to do something on my mac and it doesn't have any GPUs.

Could you please release a version that only to use the CPU?

Thank you so much!

**Comment by antigol** [comment]
The cpu version is not optimized at all and thus very slow.
You don't need `pynvrtc` and `cupy` when you run on cpu.

**Comment by zhixuanli** [comment]
Thank you!
