### ISSUE TITLE
S2 convolution vs. SO3 convolution

### ISSUE THREAD

**Issue by meder411** [jonas-koehler/s2cnn#19]
Could you please clarify the difference between S2 convolutions and SO3 convolutions? From what I gather from the two papers, an S2 convolution should happen on a spherical input (e.g. an equirectangular image), but all subsequent convolutions should be SO3 convolutions. This is because, while the S2 convolution is an operation on the sphere (i.e. in S2), it involves a rotation in SO3. Hence, the output is a function of SO3 and requires a slightly different convolution operation. Is that accurate?

Nonetheless, in practice, does this just mean that we apply an S2 convolution to the input and SO3 convolutions to the subsequent feature maps?

**Comment by mariogeiger** [comment]
Yes that is correct :-)
