### ISSUE TITLE
Error occurred in the process of installation

### ISSUE THREAD

**Issue by sherkwast** [jonas-koehler/s2cnn#2]
When I run the command `python setup.py install`, I got output as follows

> running install
running bdist_egg
running egg_info
writing s2cnn.egg-info/PKG-INFO
writing dependency_links to s2cnn.egg-info/dependency_links.txt
writing requirements to s2cnn.egg-info/requires.txt
writing top-level names to s2cnn.egg-info/top_level.txt
reading manifest file 's2cnn.egg-info/SOURCES.txt'
writing manifest file 's2cnn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying s2cnn/ops/gpu/lib_cufft/__init__.py -> build/lib.linux-x86_64-3.6/s2cnn/ops/gpu/lib_cufft
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.6/s2cnn.ops.gpu.lib_cufft._lib_cufft.c'
already up-to-date
building 's2cnn.ops.gpu.lib_cufft._lib_cufft' extension
gcc -pthread -B /home/whu/apps/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/whu/apps/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/whu/apps/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/whu/apps/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/whu/apps/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/s2cnn.ops.gpu.lib_cufft._lib_cufft.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/s2cnn.ops.gpu.lib_cufft._lib_cufft.o
gcc -pthread -B /home/whu/apps/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/whu/apps/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/whu/apps/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/whu/apps/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/whu/apps/anaconda3/include/python3.6m -c /home/whu/Documents/s2cnn/s2cnn/ops/gpu/plan_cufft.c -o build/temp.linux-x86_64-3.6/home/whu/Documents/s2cnn/s2cnn/ops/gpu/plan_cufft.o
gcc -pthread -shared -B /home/whu/apps/anaconda3/compiler_compat -L/home/whu/apps/anaconda3/lib -Wl,-rpath=/home/whu/apps/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/s2cnn.ops.gpu.lib_cufft._lib_cufft.o build/temp.linux-x86_64-3.6/home/whu/Documents/s2cnn/s2cnn/ops/gpu/plan_cufft.o -lcufft -o build/lib.linux-x86_64-3.6/s2cnn/ops/gpu/lib_cufft/_lib_cufft.abi3.so
/home/whu/apps/anaconda3/compiler_compat/ld: cannot find -lcufft
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by XGBoost** [comment]
I have the same error, so what is the version of the dependent libraries?

**Comment by sherkwast** [comment]
Dependences? Cuda 9.1,  cudnn 7, torch 0.3.1.post2

**Comment by ixiaoli** [comment]
I have the same error, then I input this:
sudo ln -s /usr/local/cuda-8.0/lib64/libcufft.so /usr/local/lib/libcufft.so,
it work well.

**Comment by XGBoost** [comment]
@ixiaoli 
I follow your steps, it works well
thank you very much
