### ISSUE TITLE
shrec17 dataset ProjectOnSphere normalization

### ISSUE THREAD

**Issue by JiahuiLei** [jonas-koehler/s2cnn#32]
Hi, thank you for sharing the code! I'm trying to generate spherical map from ShapeNetCore, and I have one question when running your shrec17 example, in file `dataset.py` in shrec17 in examples, from line 167 to 178
`        im[0] -= 0.75
        im[0] /= 0.26
        im[1] -= 0.59
        im[1] /= 0.50
        im[2] -= 0.54
        im[2] /= 0.29
        im[3] -= 0.52
        im[3] /= 0.19
        im[4] -= 0.80
        im[4] /= 0.18
        im[5] -= 0.51
        im[5] /= 0.25 `
Are these lines a special case designed to normalize data on shrec17? Or what does these lines means? So I can move it safely. Thank you very much!

**Comment by mariogeiger** [comment]
> designed to normalize data on shrec17?

yes
