### ISSUE TITLE
some question when I run gendata.py in /examples/mnist folder

### ISSUE THREAD

**Issue by townblack** [jonas-koehler/s2cnn#38]
When I run gendata.py with no rotation in training data and test data with the command :

            python3 gendata.py --no_rotate_train --no_rotate_test                

 And I visualize some results, but some images generated seem to has nothing to do with the original images. Some results are like these:
![Figure_1](https://user-images.githubusercontent.com/33544832/59372089-5057c780-8d79-11e9-8d5c-96cd3fc341c3.jpeg)

![Figure_2](https://user-images.githubusercontent.com/33544832/59372094-5483e500-8d79-11e9-8d79-88907b9a3f16.jpeg)

![Figure_3](https://user-images.githubusercontent.com/33544832/59372099-577ed580-8d79-11e9-9902-f3dd29c4bbd7.jpeg)

I think the spherical images(right) are strange, there has nothing to do with the original images(left). I also test the algorithm on some other image:
![Figure_4](https://user-images.githubusercontent.com/33544832/59371395-79775880-8d77-11e9-828d-bdec7425208c.jpeg)

Obviously, there is something wrong with gendata.py, but I can not figure out what is wrong, so can you explain it?

**Comment by jonas-koehler** [comment]
I just ran it on my laptop. If I see it right, these "weird result" are just coming from the distortion introduced by the [stereographic projection](https://en.wikipedia.org/wiki/Stereographic_projection). As written in the paper `one in which each digit is projected on the northern hemisphere and one in
which each projected digit is additionally randomly rotated` (p.6).  As the two coordinates of the spherical image correspond to polar and azimuth angle, a projection onto a pole must end up either in the top or the bottom of the image. For the digits this can introduce significant distortion (the whole point of the architecture ;-)), but if you closely inspect your weird images, they make a lot of sense (e.g. the topology of the 0 is wrapped around the pole, the "hole" of the 9 is clearly visible, as is the curves of the 3). If you inspect your own image, you can see that it just corresponds to the original image, just wrapped around one pole.

If you inspect randomly rotated images/digits (without the flags activated), you will recognize them easier in the cases where the random rotation of the grid rotation pushes them away from the poles. Then you will see pictures like those in figure 4 of the original paper. To test, that those images should indeed correspond to the original images, just wrapped around the pole of the sphere, you can rotate them (e.g. in fourier space as given in the examples) and see how they change according to changes of azimuth and polar angles.

**Comment by townblack** [comment]
Thanks a lot, Your explanation makes it clear for me to understand. I will have a try as you mentioned.

**Comment by mariogeiger** [comment]
![59371395-79775880-8d77-11e9-828d-bdec7425208c](https://user-images.githubusercontent.com/333780/59450295-2fd74e00-8e09-11e9-9bbb-60bcb401f5e8.jpeg)

The center of the image (green dot) is mapped to the pole (green line).
The four corners (other colored dots) are mapped to the equator.

**Comment by townblack** [comment]
Thank you very much! It helps me to understand the projection process.
