### ISSUE TITLE
SyntaxError: only named arguments may follow *expression

### ISSUE THREAD

**Issue by zhaofenqiang** [jonas-koehler/s2cnn#4]
Hi, I was going to run a simple example [main.py](https://github.com/jonas-koehler/s2cnn/blob/master/examples/equivariance_error/main.py). 

The environment is: Ubuntu 16.04, python2.7.12 in Anaconda. cuda9.0.

And I have installed s2cnn successfully by 
```
python setup.py install
```
The output of this command is:

> running install
running bdist_egg
running egg_info
writing requirements to s2cnn.egg-info/requires.txt
writing s2cnn.egg-info/PKG-INFO
writing top-level names to s2cnn.egg-info/top_level.txt
writing dependency_links to s2cnn.egg-info/dependency_links.txt
reading manifest file 's2cnn.egg-info/SOURCES.txt'
writing manifest file 's2cnn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying s2cnn/ops/gpu/lib_cufft/__init__.py -> build/lib.linux-x86_64-2.7/s2cnn/ops/gpu/lib_cufft
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/s2cnn.ops.gpu.lib_cufft._lib_cufft.c'
already up-to-date
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/s2cnn
creating build/bdist.linux-x86_64/egg/s2cnn/utils
copying build/lib.linux-x86_64-2.7/s2cnn/utils/complex_utils.py -> build/bdist.linux-x86_64/egg/s2cnn/utils
copying build/lib.linux-x86_64-2.7/s2cnn/utils/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn/utils
copying build/lib.linux-x86_64-2.7/s2cnn/utils/cuda_utils.py -> build/bdist.linux-x86_64/egg/s2cnn/utils
creating build/bdist.linux-x86_64/egg/s2cnn/nn
creating build/bdist.linux-x86_64/egg/s2cnn/nn/soft
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/so3_rotation.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/s2_conv.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/so3_conv.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft
creating build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/gpu/s2_fft.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/gpu/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/gpu/so3_fft.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/so3_integrate.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft
copying build/lib.linux-x86_64-2.7/s2cnn/nn/soft/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn/nn/soft
copying build/lib.linux-x86_64-2.7/s2cnn/nn/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn/nn
creating build/bdist.linux-x86_64/egg/s2cnn/ops
copying build/lib.linux-x86_64-2.7/s2cnn/ops/s2_localft.py -> build/bdist.linux-x86_64/egg/s2cnn/ops
copying build/lib.linux-x86_64-2.7/s2cnn/ops/so3_localft.py -> build/bdist.linux-x86_64/egg/s2cnn/ops
creating build/bdist.linux-x86_64/egg/s2cnn/ops/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/ops/gpu/torchcufft.py -> build/bdist.linux-x86_64/egg/s2cnn/ops/gpu
creating build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/lib_cufft
copying build/lib.linux-x86_64-2.7/s2cnn/ops/gpu/lib_cufft/_lib_cufft.so -> build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/lib_cufft
copying build/lib.linux-x86_64-2.7/s2cnn/ops/gpu/lib_cufft/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/lib_cufft
copying build/lib.linux-x86_64-2.7/s2cnn/ops/gpu/so3_mm.py -> build/bdist.linux-x86_64/egg/s2cnn/ops/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/ops/gpu/s2_mm.py -> build/bdist.linux-x86_64/egg/s2cnn/ops/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/ops/gpu/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn/ops/gpu
copying build/lib.linux-x86_64-2.7/s2cnn/ops/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn/ops
copying build/lib.linux-x86_64-2.7/s2cnn/__init__.py -> build/bdist.linux-x86_64/egg/s2cnn
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/utils/complex_utils.py to complex_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/utils/cuda_utils.py to cuda_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/so3_rotation.py to so3_rotation.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/s2_conv.py to s2_conv.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/so3_conv.py to so3_conv.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu/s2_fft.py to s2_fft.pyc
  File "build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu/s2_fft.py", line 28
    output = output.view(-1, *batch_size, 2) # [l * m, ..., complex] (nspec, ..., 2)
SyntaxError: only named arguments may follow *expression
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu/so3_fft.py to so3_fft.pyc
  File "build/bdist.linux-x86_64/egg/s2cnn/nn/soft/gpu/so3_fft.py", line 29
    output = output.view(-1, *batch_size, 2) # [l * m * n, ..., complex]
SyntaxError: only named arguments may follow *expression
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/so3_integrate.py to so3_integrate.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/soft/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/nn/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/s2_localft.py to s2_localft.pyc
  File "build/bdist.linux-x86_64/egg/s2cnn/ops/s2_localft.py", line 29
    result = result.view(*sz[:-1], n_spectral, 2)  # shape (..., n_spectral, 2)
SyntaxError: only named arguments may follow *expression
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/so3_localft.py to so3_localft.pyc
  File "build/bdist.linux-x86_64/egg/s2cnn/ops/so3_localft.py", line 39
    result = result.view(*sz[:-1], n_spectral, 2)  # shape (..., n_spectral, 2)
SyntaxError: only named arguments may follow *expression
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/torchcufft.py to torchcufft.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/lib_cufft/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/so3_mm.py to so3_mm.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/s2_mm.py to s2_mm.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/__init__.py to __init__.pyc
creating stub loader for s2cnn/ops/gpu/lib_cufft/_lib_cufft.so
byte-compiling build/bdist.linux-x86_64/egg/s2cnn/ops/gpu/lib_cufft/_lib_cufft.py to _lib_cufft.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying s2cnn.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s2cnn.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s2cnn.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s2cnn.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s2cnn.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/s2cnn-1.0.0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing s2cnn-1.0.0-py2.7-linux-x86_64.egg
Removing /home/zfq/anaconda2/lib/python2.7/site-packages/s2cnn-1.0.0-py2.7-linux-x86_64.egg
Copying s2cnn-1.0.0-py2.7-linux-x86_64.egg to /home/zfq/anaconda2/lib/python2.7/site-packages
s2cnn 1.0.0 is already the active version in easy-install.pth
Installed /home/zfq/anaconda2/lib/python2.7/site-packages/s2cnn-1.0.0-py2.7-linux-x86_64.egg
Processing dependencies for s2cnn==1.0.0
Searching for cffi==1.7.0
Best match: cffi 1.7.0
Adding cffi 1.7.0 to easy-install.pth file
Using /home/zfq/anaconda2/lib/python2.7/site-packages
Searching for pycparser==2.14
Best match: pycparser 2.14
Adding pycparser 2.14 to easy-install.pth file
Using /home/zfq/anaconda2/lib/python2.7/site-packages
Finished processing dependencies for s2cnn==1.0.0

And then I run 
```
python examples/equivariance_error/main.py 
```
the error is:

> Traceback (most recent call last):
  File "examples/equivariance_error/main.py", line 12, in <module>
    from s2cnn.ops.s2_localft import equatorial_grid as s2_equatorial_grid
  File "/home/zfq/s2cnn/s2cnn/ops/s2_localft.py", line 29
    result = result.view(*sz[:-1], n_spectral, 2)  # shape (..., n_spectral, 2)
SyntaxError: only named arguments may follow *expression

So could anyone please give me some suggestions about how to solve this problem? Thank you very much!

**Comment by zhixuanli** [comment]
May be you should use Python3.5 or 3.6?

Here's my blog recording the installation process, may be helpful~

**Comment by zhaofenqiang** [comment]
@zhixuanli Thank you very much! The blog is a great help to me.
I reinstalled all the dependencies, and the problem was solved. I think it is exactly the python version's problem...

For your reference, I am using python 3.6 in anaconda3, and a anaconda virtual environment including all these dependencies (cupy torchvision lie_learn pynvrtc trimesh pyembree)  is recommended.
