### ISSUE TITLE
How to choose different grid

### ISSUE THREAD

**Issue by Syhzs** [jonas-koehler/s2cnn#45]
Thanks for your work. I know the differences between different grid. But I don't know how to choose different grid. It both seems Ok  when I use it. Could you give me some advice about when should I use near identity grid  or equatorial grid?

**Comment by mariogeiger** [comment]
local vs non local filters... we don't know when it is more appropriate to use one or the other, sorry.

**Comment by Syhzs** [comment]
ok thanks for your reply
